Lint/FormatParameterMismatch:
  Exclude:
    - 'test/lvm/unittests/mock.rb'

Lint/UselessAssignment:
  Exclude:
    - 'resources/nimclient.rb'

Metrics/BlockNesting:
  Max: 4

Metrics/ParameterLists:
  Max: 6

Naming/AccessorMethodName:
  Exclude:
    - 'libraries/patch_mgmt.rb'
    - 'libraries/storage_objects.rb'
    - 'providers/altdisk.rb'
    - 'test/lvm/unittests/mock.rb'

Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'test/lvm/unittests/tc_aix_storage_objects.rb'
    - 'test/lvm/unittests/tc_storage_objects.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'libraries/lvmobj_fs.rb'
    - 'libraries/lvmobj_lv.rb'
    - 'libraries/lvmobj_vg.rb'
    - 'libraries/patch_mgmt.rb'
    - 'providers/altdisk.rb'
    - 'providers/bootlist.rb'
    - 'providers/multibos.rb'
    - 'providers/subsystem.rb'
    - 'resources/chdev.rb'
    - 'resources/nimclient.rb'
    - 'resources/nimviosupdate.rb'
    - 'resources/no.rb'
    - 'resources/tunables.rb'
    - 'test/lvm/unittests/mock.rb'

Style/NonNilCheck:
  Exclude:
    - 'test/lvm/unittests/ts_all.rb'
